#!/bin/sh

WIRE=$1
WIDTH=${2:-1.0}
YRAN1=$3
if [ -z "$YRAN1" -o "$YRAN1" = ":" ]; then
  YRAN1="-0.025:0.140"
fi
YRAN2=$4
if [ -z "$YRAN2" -o "$YRAN2" = ":" ]; then
  YRAN2="-0.0105:0.0315"
fi
OFF="$5"
ACT=$6

if [ -z "$WIRE" -o "$WIRE" = "-h" ]; then
  echo Usage: $0  [WIRE [WIDTH [YRAN1 [YRAN2 [OFF [ACT]]]]]]
  echo "   WIRE = center of wire range: 0 is central, +/-1 are first 1st neighbors, ...."
  echo "  WIDTH = width of wire range, e.g. 1 for one cell, ...."
  echo "  YRAN1 = YMIN:YMAX for raw response plot"
  echo "  YRAN2 = YMIN:YMAX for smeared response plot"
  echo "    OFF = offset(s) [0.1 us] used in rebinning smeared response to 2 MHz"
  echo "    ACT = draw to draw plots or post to post plots"
  exit 0
fi

TICK0=-20
NTICK=40

if [ ${WIRE:0:1} = "s" ]; then
  WIRE=${WIRE:1}
  SYMM=true
  echo Symmetrizing wire $WIRE
else
  SYMM=
fi
CELL=
if [ $WIRE -eq $WIRE ] 2>/dev/null; then
  CELL=$((WIRE+10))
fi
YMIN1=$(echo $YRAN1 | sed 's/:.*//g')
YMAX1=$(echo $YRAN1 | sed 's/.*://g')
CHK=$(bc <<< $YMAX1'>'$YMIN1 2>>/dev/null)
if [ "$CHK" != 1 ]; then
  echo Invalid range 1: $YRAN1
  exit 1
fi

YMIN2=$(echo $YRAN2 | sed 's/:.*//g')
YMAX2=$(echo $YRAN2 | sed 's/.*://g')
CHK=$(bc <<< $YMAX2'>'$YMIN2 2>>/dev/null)
if [ "$CHK" != 1 ]; then
  echo Invalid range 1: $YRAN2
  exit 1
fi

AWIRE=$WIRE
SIGN="p"
if [ ${WIRE:0:1} = "-" ]; then
  AWIRE=${WIRE:1}
  SIGN="m"
fi
if [ -n "$SYMM" ]; then
  SIGN="s"
fi
SWIR=$(bc -l <<<'1000*'$AWIRE | sed 's/\..*//')
while [ ${#SWIR} -lt 4 ]; do SWIR=0$SWIR; done
SWIR=${SIGN}$SWIR

SWID=$(bc -l <<<'1000*'$WIDTH | sed 's/\..*//')
while [ ${#SWID} -lt 4 ]; do SWID=0$SWID; done

SBIN=${SWIR}w$SWID
BAS1=response$SBIN
BAS2=${BAS1}Smeared
BAS3=${BAS2}Rebin131
SCELL=$CELL
if [ ${#SCELL} -eq 1 ]; then SCELL=0$SCELL; fi
BAS4=wirecellResponse$SCELL

DIR=$WIRECELL_KERNEL_DIR/root
if [ -n "$SYMM" ]; then
  root.exe -b -q $DIR'/plotResponseSymmetric.C('$WIRE', '$WIDTH', '$YMIN1', '$YMAX1')'
else
  root.exe -b -q $DIR'/plotResponse.C('$WIRE', '$WIDTH', '$YMIN1', '$YMAX1')'
fi

# Smear, rebin and plot response from text files.
echo cell $CELL
echo $BAS1 $BAS4
if [ -r $BAS1.tpad ]; then
  root.exe -b -q $DIR'/cesmearTpad.C("'$BAS1'", '$YMIN2', '$YMAX2')'
  if [ -n "$OFF" ]; then
    for IOFF in $OFF; do
      root.exe -b -q $DIR'/rebinTpad.C("'$BAS2'", "'$SBIN'", '$IOFF', '$TICK0', '$NTICK')'
    done
  fi
  if [ -n "$CELL" ]; then
    root.exe -b -q $DIR'/plotWirecell.C('$CELL', 106, 146, -0.00215, 0.00645)'
  fi
else
  echo File not found: $BAS1.tpad 
  exit 1
fi

if [ "$ACT" = draw ]; then
  echo Drawing plots
  view $BAS1.png &
  view $BAS2.png &
  view $BAS3.png &
  view $BAS4.png &

elif [ "$ACT" = post ]; then
  echo Posting plots
  WDIR=~/wwwdune/protodune/response/wire$SWIR
  rm -rf $WDIR
  mkdir $WDIR
  for BAS in $BAS1 $BAS2 $BAS4; do
    cp $BAS.png $WDIR
    cp $BAS.tpad $WDIR
  done
  cp $BAS2-*.txt $WDIR
  cp ${BAS2}Rebin*.png $WDIR
  makeIndex $WDIR
  makeIndex $WDIR/.. k

else
  echo "Ignoring invalid action" $ACT
fi
